### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by amorenew** [ncondo/SDCND-Prerequisites#1]
Hi good work
i have updated my spreadsheet with more resources from caltec, mit and others
https://docs.google.com/spreadsheets/u/1/d/13QQinPFhU9DwujctXS0A7un0up4N5BNyUDZwxK4I6hg/edit#gid=0

**Comment by ncondo** [comment]
Hi,
Thanks for sharing. If you fork the repo and submit a pull request I can merge the updates

**Comment by amorenew** [comment]
@ncondo actually i don't have time right now because i already started my SDC ND - January cohort
but i will make a medium blog and writing about my feedback about every source i have finished.

**Comment by ncondo** [comment]
@amorenew sounds good, best of luck with the course. I'm actually working on project 3 right now :)
